# source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'GLChart_Example', :exclusive => true do
  pod "GLChart", :path => "../"
end

target 'GLChart_Tests', :exclusive => true do
  pod "GLChart", :path => "../"

  
end
